a = input(' Digite algo : ')
print(' O tipo primitivo desse valor é ',type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ',a.isnumeric())
print('É alfabético? ',a.isalpha())
print('É alfanumerico? ',a.isalnum())
print('Está em maiúsculos? ',a.isupper())
print('Está em minusculos? ',a.islower())
print('Está capitalizada? ',a.istitle())
